### ISSUE TITLE
postcss configuration for css-loader

### ISSUE THREAD

**Issue by veeramarni** [sysgears/spin.js#14]
Thanks for releasing `0.4.11` to support `css` out of the box. I'm getting following error, as it is looking for `postcss.config.js`. Should it be by default taken care of it and may provide way to customize it if needed. In my case, it is really not required for using `css-loader`.

Error
--
```
ERROR in ./node_modules/css-loader?{"sourceMap":true,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true}!./servers/frontend-server/src/index.css
Module build failed: Error: No PostCSS Config found in: /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/servers/frontend-server/src
    at /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/fullstack-pro/node_modules/postcss-load-config/index.js:51:26
    at <anonymous>
 @ ./servers/frontend-server/src/index.css 4:14-150 18:2-22:4 19:20-156
 @ ./servers/frontend-server/src/index.tsx
 @ multi ./servers/frontend-server/src/index.tsx
```

**Comment by vlasenko** [comment]
@veeramarni Thanks, that would be the desired behavior, I will take a look to implement it

**Comment by vlasenko** [comment]
@veeramarni With `spinjs@0.4.14` if `postcss-loader` is not installed into project dependencies it will not be used

**Comment by veeramarni** [comment]
@vlasenko thank you, will test it.
